#!/bin/sh
#
# This script is used by the buildbot master to create a tarball
# of the freedroidRPG.app but without all the data files, and then
# transfer it to the linux worker that will create the final dmg.
#
# This 2 steps process is needed because the first step is executed
# on a MacMini with a low internet bandwidth, too low to transfer a whole
# dmg in a reasonable time.

APPDIR=freedroidRPG.app
ARCHIVE=lite-freedroidRPG.app.tgz

[ -f ${ARCHIVE} ] && rm -f ${ARCHIVE}
tar -cvzf ${ARCHIVE} --exclude Contents/data --exclude Contents/locale --exclude Contents/lua_modules ${APPDIR}
